# Generated by Django 5.1.6 on 2025-04-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('grade', models.CharField(max_length=2)),
                ('report', models.FileField(upload_to='reports/')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
